### Create User
GET http://localhost:3001/hello HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJYdmhqeF8tanJndUNaeTZEdjI4cHNQNkFzWldqbnpTOUFfNklrdVczbmtrIiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULmRob3RuUmI4andlNmpwQVhlMUhRNGlPbDZpMDlQWDNHRVJKMldnOXV5N28iLCJpc3MiOiJodHRwczovL2Rldi02NjA5MTg2OS5va3RhLmNvbS9vYXV0aDIvZGVmYXVsdCIsImF1ZCI6ImFwaTovL2RlZmF1bHQiLCJpYXQiOjE2NTE0OTEyNjMsImV4cCI6MTY1MTQ5NDg2MywiY2lkIjoiMG9hNHZvZ2V1dk5RN0pubG01ZDciLCJ1aWQiOiIwMHU0dnA3NHA4bXBYMjRVQTVkNyIsInNjcCI6WyJvcGVuaWQiLCJwcm9maWxlIiwiZW1haWwiXSwiYXV0aF90aW1lIjoxNjUxNDkxMjYyLCJzdWIiOiJhbGVrcy50cnBrb3Zza2lAc21pbGVob29kLm9yZyIsInBlcm1pc3Npb25zIjpbIlJlYWQiLCJEZWxldGUiLCJXcml0ZSJdfQ.ZMYBUUR0Ff1ToAnzePFaN6Y4sbUgO0He-ltchEekFyQPajLMM4cOaKa-XzqMGIuvfWH7tMSl9Sry_c76l9CbxIPWfBUn2I1cVTtO_e-zc5zbXqz4LHsHTJYnHjeOkCSXEYfMp7-3rkA4Po6AA06Q1JpSqR90lNy8LF79W3eGnasWb9WsJZr5yMYGtKgSQ4RXbF9dpfEpDW9gOAgRescF98yxSdXlRhMvbMG9KTVNVYTWOI5Hf6sRSb4FmT7Uju8Ke939v3W0DZo6vMz6VNkM0k-IFD5ghZjk40yCRKYcQylrib-paKiB4t7BNz9v_jz2nzkDAqaUdb6lRSgyLkstZg

{
    "email": "test4@test.com",
    "password": "P@ssword1"
}