### Create User
GET http://localhost:3001/hello HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJYdmhqeF8tanJndUNaeTZEdjI4cHNQNkFzWldqbnpTOUFfNklrdVczbmtrIiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULjZaMVNRUnZPeEJTRzc4RDJkVkJ2SzZFUXhPZWd0aEJBdGptcTNJcDhPR2ciLCJpc3MiOiJodHRwczovL2Rldi02NjA5MTg2OS5va3RhLmNvbS9vYXV0aDIvZGVmYXVsdCIsImF1ZCI6ImFwaTovL2RlZmF1bHQiLCJpYXQiOjE2NTE0ODY5MzMsImV4cCI6MTY1MTQ5MDUzMywiY2lkIjoiMG9hNHZvZ2V1dk5RN0pubG01ZDciLCJ1aWQiOiIwMHU0dnA3NHA4bXBYMjRVQTVkNyIsInNjcCI6WyJvcGVuaWQiLCJwcm9maWxlIiwiZW1haWwiXSwiYXV0aF90aW1lIjoxNjUxNDg2OTMyLCJzdWIiOiJhbGVrcy50cnBrb3Zza2lAc21pbGVob29kLm9yZyIsInBlcm1pc3Npb25zIjpbIlJlYWQiLCJEZWxldGUiLCJXcml0ZSJdfQ.XMuKRUyQ7HWcFDN5Q4n2EIyogG3yiWEVES67BrncfvZA941QRp8kOV7gvpiptG8S2UN_FJwfteLyFVQTDfZmLwJb_aB1qTuOxbAedBkNCzbjfO-HOx4sMh9me0jphIc6dp-Y5d_DipQBnWskytV-uikvhL2zSTFKkYjJvYivuNMEfC2L8kaVXMe1VEgVVQOEx9k_ewiOjjEpBINLpkFNf_wgC0XBEziqllRvxHM_Eltlg3bth6A5zq8FJU3I6k5YYfTYsRCbVLutmvoinLtaljdmJAhVhNVtGF5M7efL58uHq8ooD9HvcQSP8B1RnhpwCntN_kO0uRkPp3Zd6usViQ

{
    "email": "test4@test.com",
    "password": "P@ssword1"
}